### ISSUE TITLE
Framework de Telegram

### ISSUE THREAD

**Issue by msolefonte** [serpean/iCalendar#8]
This is just a QUESTION.

Veo que estáis utilizando [`node-telegram-bot-api`](https://github.com/yagop/node-telegram-bot-api), estando también disponible para NodeJS [`telegraf`](https://github.com/telegraf/telegraf). ¿Es puro azar o tenéis referencias de que una alternativa es mejor que otra?

Pregunta seria, me interesa.

**Comment by serpean** [comment]
En este momento es puro azar pues el una primera implementación en fase de pruebas para la autenticación, ya que el encargado de seleccionar un framework para el bot es @Bullcaos .

**Comment by msolefonte** [comment]
Para mis librerías `AMQP2Telegram` y `Telegram2AMQP` de Node.js utilicé `telegraf`, por eso lo digo. 

Principalmente me interesa saber si habéis buscado algo para saber si puedo mejorar lo que tengo. Por lo pronto veo que `node-telegram-bot-api` tiene más Stars y más Forks, luego supongo que más usuarios.

**Comment by Bullcaos** [comment]
En principio, ambos son válidos por igual, de hecho, consideramos emplear ambos en la fase de desarrollo, pero para un bot rápido como el de pruebas de autenticación, cuyo fin es ver como se comporta Telegram con los bots, utilizamos ese porque era el que teníamos "mas a mano".

**Comment by serpean** [comment]
Al final el equipo ha decido cambiar el bot de `node-telegram-bot-api` a `telegraf` por los siguientes motivos.

1. `node-telegraam-bot-api` usaba librerías deprecated.
1. LLevaremos a cabo el uso de una librería escrita para telegraf.
1. Las opciones que ofrece telegraf son más sencillas a la hora de llevar a cabo un Wizard que ayude a la creación de un evento.
1. En general, después de un análisis un poco más detenido, framework más actualizado y sencillo para llevar a cabo la implementación de un bot para telegram.

**Comment by msolefonte** [comment]
Pues no me parece bien porque en `telegraf` no me aprobaron un PR.

**Comment by serpean** [comment]
Respuesta resuelta
